### ISSUE TITLE
Windows Defender Smartscreen attempts to block app from running.

### ISSUE THREAD

**Issue by Kuiriel** [EXKing-Editor/EXKing-Editor#20]
Just letting you know that attempting to open the exe triggers a Windows Defender popup. For Ex-King-Editor-0.3.1-alpha.exe

"Windows Defender Smartscreen prevented an unrecognized app from starting."

Not sure why. Virustotal says clear except for

Jiangmin - Trojan.Sdum.apa - SecureAge - Malicious

**Comment by GGLinnk** [comment]
Essentially, when a file hasn't been extracted from an archive like a zip or rar file, Windows treats it as a foreign executable. In this case, Windows proceeds to check the program's signature. If the program is not signed, Windows informs you about it.

SmartScreen, is not an antivirus program. It serves as a mechanism by Microsoft to indicate that the program in question has not obtained a license from Microsoft or its partners.

**Comment by ArchLeaders** [comment]
Yeah, this is just a side effect of windows with unsigned assemblies. Zipping it has never fixed it for me though.

The reason it's not signed is just because I'm not willing to spend $100/yr for a digital signature.

---

As for the virus total result, not really sure what would trigger that. Everything is open source though, you can check for yourself and build from source if you have concerns.
