### ISSUE TITLE
Why is a full game dump (RomFS) required?

### ISSUE THREAD

**Issue by sSomename** [EXKing-Editor/EXKing-Editor#22]
Why is the romfs required to edit files. Unlike a mod manager which has _clear_ reasons for such a requirement this is a tool for editing files from the game.

**Comment by ArchLeaders** [comment]
Every file that is compressed with zStandard (`.zs`) requires a dictionary file (`ZsDic.pack.zs`) to decompress. But, since you would need to dump the game to get those files anyway, and with future developments in mind to use more files. It seemed sensible to require a full game dump just for simplicity.

At any rate, you'll need it eventually for a mod merger.

**Comment by sSomename** [comment]
Thanks for the quick and clear explanation.
