### ISSUE TITLE
Modifying MSBTs for other games via this?

### ISSUE THREAD

**Issue by miraclematters** [EXKing-Editor/EXKing-Editor#57]
Is it possible to open and edit other MSBT files in NX-Editor? I've only tried it with TOTK which worked fine, but I wouldn't know what to do to set it up for other games

**Comment by ArchLeaders** [comment]
> Is it possible to open and edit other MSBT files in NX-Editor? I've only tried it with TOTK which worked fine, but I wouldn't know what to do to set it up for other games.

Should work for other games. The library currently has some limitations, but I'm working on a rewrite which should support most MSBT files. The current library only has support for LBL1 and TXT2 sections, BotW for example uses ATR1 so that may not work. 

I'll probably update to the new MSBT library though, which has ATR1 support and I'll try and implement other sections sometime as well.

---

As far as setup goes, it's just a matter of enabling EpdPlugin in the launcher.

**Comment by miraclematters** [comment]
Thank you!
It seems to crash when trying to modify Miitopia's MSBTs, would you happen to know why?

**Comment by ArchLeaders** [comment]
> Thank you! It seems to crash when trying to modify Miitopia's MSBTs, would you happen to know why?

Not off hand. If you send me the file I can look into it though.

**Comment by miraclematters** [comment]
do you have a discord? i can send it to you on there!

**Comment by ArchLeaders** [comment]
> do you have a discord? i can send it to you on there!

I do indeed: https://discord.gg/8Saj6tTkNB
